# Generated by Django 4.2.4 on 2023-08-16 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_rename_photo_food_food_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_description',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='food',
            name='food_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='food_price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='food',
            name='food_pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='food_rate',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='food',
            name='food_time',
            field=models.IntegerField(default=None),
        ),
    ]
