# Generated by Django 4.2.4 on 2023-08-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_food_food_description_food_food_name_food_food_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_pub_date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_rate',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_time',
            new_name='time',
        ),
    ]
