# Generated by Django 4.2.4 on 2023-08-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_rename_food_description_food_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
