# Generated by Django 4.2.4 on 2023-08-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_food_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], default='D', max_length=10),
        ),
    ]
