# Generated by Django 4.2.4 on 2023-08-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('summary', models.TextField(max_length=500)),
                ('date', models.TimeField(auto_now_add=True)),
                ('tag', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('photo', models.ImageField(max_length=200, upload_to='')),
            ],
        ),
    ]
